config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :owners, :controllers => { :registrations => "owners"}

  devise_scope :owner do
    authenticated :owner do
      root :to => 'restos#show', as: :authenticated_root
    end
  end

  root to: 'home#index'

  
  resources :restos do
    member do 
      get :data
      post :publish_resto
      post :unpublish_resto
    end
    collection do
      get :get_restos
    end
    resources :menus
    resources :promos
    resources :configurations
  end

  get "api/restos/:id" => "restos_api#show_resto"

  get "api/resto/:id/"  => "restos#show_resto"

  get "api/resto/:id/menus" => "restos_api#menus"

  get "api/resto/:id/promos" => "restos_api#promos"

  post "api/search/:data" => "restos_api#search"

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :resto

  has_attached_file :avatar, :default_url => "img/missing.png",styles: {
    thumb: '160x160>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def image_url
    avatar.url(:medium)
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu,:set_resto ,only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_owner!

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.where(resto_id: current_owner.resto.id).order("updated_at DESC")
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)
    @menu.resto_id = current_owner.resto.id

    respond_to do |format|
      if @menu.save
        format.html { redirect_to resto_menus_path, notice: 'Menu Creado Exitosamente.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to resto_menus_path, notice: 'Menu Actualizado Correctamente.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to resto_resto_menus_path, notice: 'Menu Eliminado Exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def set_resto
      if @menu.resto_id
        @resto = Resto.find(@menu.resto_id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:avatar,:name,:price,:entrada,:bebestible,:fondo,:postre)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<script type="text/javascript">
   $("#new_menu").submit(function(){
    $(".spiner").fadeIn();
    $(".spiner").spin({color: "#fff", speed: 1.8})
    $("input:submit").prop("disabled", true).css("background","#ccc")

  });
</script>

<div class="col-sm-12">
	<div class="form-item">
	<%= form_for([current_owner.resto,@menu]) do |f| %>
	     <div class="col-sm-4">
		     <div class="form-field">
		        <p>Nombre :</p>
		        <%= f.text_field :name ,:maxlength => 50 ,:size => "30"%>
		     </div>
		     <div class="form-field">
		      <p>Precio :</p>
		      <%= f.text_field :price,size: "6" %>
		     </div>
		     <div class="form-field">
		      <p>Entrada :</p>
		      <%= f.text_field :entrada, size: "30" %>
		     </div>
	     </div>
			 <div class="col-sm-4">
		     <div class="form-field">
		      <p>Bebestible :</p>
		      <%= f.text_field :bebestible, size: "30" %>
		     </div>
		     <div class="form-field">
		      <p>Fondo :</p>
		      <%= f.text_field :fondo ,size: "30"%>
		     </div>
		     <div class="form-field">
		      <p>Postre :</p>
		      <%= f.text_field :postre, size: "30"%> 
		     </div>
			 </div>
			 <div class="col-sm-4">
			   <div class="form-field image">
			    <%= f.file_field :avatar %>
			   </div>
				 <div class="image-container">
					<% if @menu.new_record? %>
						<h1>Sube una imagen</h1>
					<% else %>
						<img src="<%= @menu.image_url%>">
					<% end %>
				 </div>
			 </div>
		 
   
	  <% if @menu.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

	      <ul>
	      <% @menu.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	    <div class="actions">
	      <%= f.submit ( f.object.new_record? ? "Crear Menu" : "Actualizar Menu")%>
	    </div>
	  <% end %>
	</div>
</div>

app/views/menus/_modal.html.erb
<div class="modal fade menu-modal" id="myModal<%= menu.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Editando Menu</h4>
        </div>
        <div class="modal-body menu-content">
            <div class="left-side">
            <%= form_for menu, :html => { :multipart => true } do |f| %>
             <div class="input-modal">
               <p>Nombre</p>
               <%= f.text_field :name %>
             </div>
             <div class="input-modal">
               <p>Descripción</p>
               <%= f.text_area :description , :cols => "30", :rows => "3" %>
             </div>
             <div class="input-modal">
               <p>Precio</p>
               <%= f.text_field :price %>
             </div>
             <div class="imagen-field">
               <p>Imagen</p>
               <%= f.file_field :avatar %>
             </div>
             <div class="modal-footer menu-footer">
              <div class="actions">
               <button type="button" class="btn btn-default close-btn" data-dismiss="modal">Close</button>
               <%= f.submit %>
             </div>
          </div>
            <% if menu.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(menu.errors.count, "error") %> prohibited this promo from being saved:</h2>

                <ul>
                <% menu.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

        <% end %>
            </div>
            <div class="right-side">
              <%= image_tag(menu.image_url) %>
            </div>
          </form> 
        </div>
      </div>
    </div>
  </div>

app/views/menus/edit.html.erb
<div class="contenedor">
	<div class="canvas edit-content">
	  <h1>Editando Menu</h1>
		<h1 class="subtitle"><%= @menu.name %></h1>
		<%= link_to resto_menus_path,class: "volver" do %>
			<i class="fa fa-angle-left "></i>
			<p>Volver a Menus</p>
		<% end %>
		<%= render 'form' %>
	</div>
</div>

app/views/menus/index.html.erb
<div class="contenedor content">
  <div class="canvas">
    <h1>Menus del Dia</h1>
		<h1 class="subtitle">Recuerda Actualizar los menus</h1>

<% if @menus.length > 0 %>
    <table>
      <tbody>
      <tr class="table-title">
        <td>Imagen</td>
        <td>Nombre</td>
        <td>Entrada</td>
        <td>Fondo</td>
        <td>Precio</td>
      </tr>
	        <% @menus.each do |menu| %>
						<tr class="table-row">
               <td class="mini-image"><img src="<%= menu.image_url%>"></td>
		           <td><%= menu.name %></td>
		           <td><%= menu.entrada %></td>
		           <td><%= menu.fondo %></td>
		           <td>$<%= menu.price %></td>
							 <td class="padding"><%= link_to 'Editar',edit_resto_menu_path(current_owner.resto,menu), class: "editar"%></td>
		           <td class="padding padding-right"><%= link_to 'Eliminar',resto_menu_path(current_owner.resto,menu), class: "eliminar",method: :delete, data: { confirm: '¿Estas Seguro que deseas eliminar esta Promoción?' } %></td>
		        </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
  <div>
    <h1>No hay menus todavia</h1>
  </div>
<% end %>

    <br>

    <%= link_to 'Añadir Menu', new_resto_menu_path, class: "new-item"  %>

  </div>
</div>

app/views/menus/new.html.erb
<div class="contenedor">
  <div class="canvas edit-content">
    <h1>Creando Menu</h1>
		<h1 class="subtitle">No olvides subir una fotografía</h1>

    <%= render 'form' %>

		<%= link_to resto_menus_path,class: "volver" do %>
			<i class="fa fa-angle-left "></i>
			<p>Volver a Menus</p>	
		<% end %>
  </div>
</div>

app/views/menus/show.html.erb
<h4><%= @menu.name%></h4>

<h2><%= @resto.name %></h2>
<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>