config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :owners, :controllers => { :registrations => "owners"}

  devise_scope :owner do
    authenticated :owner do
      root :to => 'restos#show', as: :authenticated_root
    end
  end

  root to: 'home#index'

  
  resources :restos do
    member do 
      get :data
      post :publish_resto
      post :unpublish_resto
    end
    collection do
      get :get_restos
    end
    resources :menus
    resources :promos
    resources :configurations
  end

  get "api/restos/:id" => "restos_api#show_resto"

  get "api/resto/:id/"  => "restos#show_resto"

  get "api/resto/:id/menus" => "restos_api#menus"

  get "api/resto/:id/promos" => "restos_api#promos"

  post "api/search/:data" => "restos_api#search"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token
  
  private
  
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
  
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :resto

  has_attached_file :avatar, :default_url => "img/missing.png",styles: {
    thumb: '160x160>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def image_url
    avatar.url(:medium)
  end

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:async,:confirmable

  has_one :resto, dependent: :destroy

  # validates :resto_name , presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :imaegeble, :polymorphic => true

  has_attached_file :avatar, styles: {
    thumb: '160x160>',
    medium: '300x300>',
    large: '800x800>'
  },

  :url => ':s3_alias_url',
  :s3_host_alias => 'd27tkdf0qa4ye1.cloudfront.net'

  validates_attachment_size :avatar, less_than: 2.megabyte

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/promo.rb
class Promo < ActiveRecord::Base
  belongs_to :resto

  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def image_url
    avatar.url(:medium)
  end

  
  def final_price
    discount = self.discount * self.price / 100
    self.price - discount
  end

end

app/models/resto.rb
class Resto < ActiveRecord::Base
  include PgSearch

  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance

  attr_accessor :distance

  belongs_to :owner
  belongs_to :resto_tipo
  has_many :promos
  has_many :menus
  has_many :subscriptions

  has_attached_file :avatar, styles: {
    thumb: '160x160>',
    medium: '300x300>',
    large: '800x800>'
  },

  :url => ':s3_alias_url',
  :s3_host_alias => 'd27tkdf0qa4ye1.cloudfront.net'

  validates_attachment_size :avatar, less_than: 2.megabyte

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  after_destroy :refresh_cache
  after_save :refresh_cache

  pg_search_scope :search, :against => [:name],:using => { :tsearch => {:prefix => true} }

  validates :details, presence: true


  def calculate_distance(location)
    self.distance = self.distance_to(location,:units=>:kms,:formula => :sphere).round(1)
  end

  def self.cached_restos
    Rails.cache.fetch("restos") { where(online: true).to_a }
  end

  def refresh_cache
    Rails.cache.delete("restos")
  end

  def set_online
    self.online = true
    save
  end

  def past_due?
    self.subscriptions.where(active: true).blank?
  end

end

app/models/resto_tipo.rb
class RestoTipo < ActiveRecord::Base
  has_many :restos
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :resto

  def self.subscribe(resto,mode,amount)
    resto.subscriptions.update_all(active: false) unless resto.subscriptions.blank?
    resto.subscriptions << Subscription.new(active: true, expiration_date: 30.days.from_now,
                                          mode: mode, amount: amount)
  end

  def cancel
    self.update(active: false)
    self.resto.update(online: false)
  end

  def self.cancel_past_dues_subscriptions
    past_due_subs = Subscription.where("expiration_date < ?", Date.today)
    past_due_subs.each do |pd|
      pd.cancel
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/carta_helper.rb
module CartaHelper
end

app/helpers/cartas_helper.rb
module CartasHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages

    html = <<-HTML

    <script type="text/javascript">
        _.each(#{messages},function(mes){
          toastr.error(mes)
        })
    </script>
    HTML

    html.html_safe
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/platos_helper.rb
module PlatosHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/helpers/restos_helper.rb
module RestosHelper
end

app/views/admins/confirmation_message.html.erb
<div class="contenedor">
  <div class="canvas">
    <h1>Solo falta un paso mas..</h1>
    <h4>Ve a tu correo,confirma tu cuenta y listo.</h4>
    <div class="resend-email">
      <a href="#">Si aun no recibes el email puedes reenviarlo desde <strong>aqui</strong></a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestoApp</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:200,300' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "shared/header" %>
<%= yield %>
  <script type="text/javascript">
    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        toastr.error(<%= raw message.inspect %>)
      <% end %>
      <% if type == "notice"%>
        toastr.success(<%= raw message.inspect %>)
      <% end %>
    <% end %>
  </script>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestoApp</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'bootstrap_and_overrides', media: 'all'%>
  <%= stylesheet_link_tag 'animate', media: 'all'%>
  <%= stylesheet_link_tag 'style', media: 'all'%>
  <%= stylesheet_link_tag 'media-queries', media: 'all'%>
  <%= stylesheet_link_tag 'form-elements', media: 'all'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:200,300' rel='stylesheet' type='text/css'>
</head>

<body>
<%= yield %>

</body>

</html>

app/views/shared/_header.html.erb
<div class="header">
  <% if @current_admin %>
    <div class="logo-admin">
      <%= image_tag("logo.png") %>
    </div>
    <div class="side-menu">
      <%= render 'shared/header_menu'%>
    </div>
    <div class="log-out">
      <li><%= link_to "cerrar sesion" , destroy_owner_session_path, method: :delete %></li>
    </div>
  <% elsif params[:controller] == 'devise/sessions'%>
    <div class="header-login">
      <div class="logo-login">
        <%= image_tag("logo-solo.png") %>
      </div>
    </div>
  <% else %>
    <div class="logo-admin">
      <%= image_tag("logo.png") %>
    </div>
  <% end %>
</div>

app/views/shared/_header_menu.html.erb
<div class="options-menu">
  <li class="<%= 'active' if params[:controller] == 'restos' %>">
    <%= link_to resto_path(current_owner.resto.id) do %>
      <i class="fa fa-home"></i>
      <span>Home</span>
    <% end %>
  </li>

  <li class="<%= 'active' if params[:controller] == 'menus' %>">
    <%= link_to resto_menus_path(current_owner.resto) do %>
      <i class="fa fa-cutlery "></i>
      <span>Menus del Día</span>
    <% end %>
  </li>

  <li class="<%= 'active' if params[:controller] == 'promos' %>">
    <%= link_to resto_promos_path(current_owner.resto) do %>
      <i class="fa fa-tags "></i>
      <span>Promociones</span>
    <% end %>
  </li>

  <li class="<%= 'active' if params[:controller] == 'configurations' %>">
    <%= link_to resto_configurations_path(current_owner.resto) do %>
      <i class="fa fa-gear "></i>
      <span>Configuracion</span>
    <% end %>
  </li>

</div>