config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :owners, :controllers => { :registrations => "owners"}

  devise_scope :owner do
    authenticated :owner do
      root :to => 'restos#show', as: :authenticated_root
    end
  end

  root to: 'home#index'

  
  resources :restos do
    member do 
      get :data
      post :publish_resto
      post :unpublish_resto
    end
    collection do
      get :get_restos
    end
    resources :menus
    resources :promos
    resources :configurations
  end

  get "api/restos/:id" => "restos_api#show_resto"

  get "api/resto/:id/"  => "restos#show_resto"

  get "api/resto/:id/menus" => "restos_api#menus"

  get "api/resto/:id/promos" => "restos_api#promos"

  post "api/search/:data" => "restos_api#search"

end

app/models/promo.rb
class Promo < ActiveRecord::Base
  belongs_to :resto

  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def image_url
    avatar.url(:medium)
  end

  
  def final_price
    discount = self.discount * self.price / 100
    self.price - discount
  end

end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_owner!

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.where(resto_id: current_owner.resto.id)
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)
    @promo.resto_id = current_owner.resto.id

    respond_to do |format|
      if @promo.save
        format.html { redirect_to resto_promos_url, notice: 'Promoción Creada Exitosamente' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to resto_promos_url, notice: 'Promoción Actualizada Exitosamente.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to resto_promos_url, notice: 'Promoción Eliminada Exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:name,:description,:price,:discount,:avatar)
    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<script type="text/javascript">
   $("#new_promo").submit(function(){
    $(".spiner").fadeIn();
    $(".spiner").spin({color: "#fff", speed: 1.8})
    $("input:submit").prop("disabled", true).css("background","#ccc")

  });
</script>
<div class="col-sm-12">
	<div class="form-item">
	  <%= form_for ([current_owner.resto, @promo]), :html => { :multipart => true } do |f| %>
			 <div class="col-sm-6">
		     <div class="form-field">
		      <p>Nombre </p>
		      <%= f.text_field :name ,:maxlength => 200 ,:size => "30"%>
		     </div>
		     <div class="form-field">
		      <p>Descripción</p>
		      <%= f.text_area :description ,:maxlength => 300 ,:size => "60x6"%>
		     </div>
			 </div>
			 <div class="col-sm-6">
		     <div class="form-field image">
				 	<p>Imagen </p>
		      <%= f.file_field :avatar %>
				 <div class="image-container">
					<% if @promo.new_record? %>
						<h1>Recuerda Subir una imagen</h1>
					<% else %>
						<img src="<%= @promo.image_url%>">
					<% end %>
				 </div>
		     </div>
			 </div>

	    <% if @promo.errors.any? %>
	      <div id="error_explanation">
	        <h2><%= pluralize(@promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

	        <ul>
	        <% @promo.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	        <% end %>
	        </ul>
	      </div>
	    <% end %>

	    <div class="actions">
	      <%= f.submit  ( f.object.new_record? ? "Crear Promoción" : "Actualizar Promoción") %>
	    </div>
	  <% end %>

	</div>
</div>

app/views/promos/edit.html.erb
<div class="contenedor">
  <div class="canvas edit-content">
    <h1>Editando Promoción</h1>
		<h1 class="subtitle"><%= @promo.name %></h1>
    
    <%= link_to resto_promos_path,class: "volver" do %>
      <i class="fa fa-angle-left "></i>
      <p>Volver a Promociones</p> 
    <% end %>
    <%= render 'form' %>


  </div>
</div>

app/views/promos/index.html.erb
<div class="contenedor content">
  <div class="canvas">
    <h1>Promociones</h1>
		<h1 class="subtitle"></h1>

<% if @promos.length > 0 %>
    <table>
      <tbody>
      <tr class="table-title">
        <td>Imagen</td>
        <td>Nombre</td>
        <td>Descripción</td>
        <td>Precio</td>
      </tr>
        <% @promos.each do |promo| %>
          <tr class="table-row">
            <td class="mini-image"><img src="<%= promo.image_url%>"></td>
            <td><%= promo.name %></td>
            <td><%= promo.description %></td>
            <td>$<%= promo.price %></td>
            <td><%= link_to 'Editar',edit_resto_promo_path(current_owner.resto,promo),class: "editar"  %></td>
            <td><%= link_to 'Eliminar', resto_promo_path(current_owner.resto,promo), class: "eliminar",method: :delete, data: { confirm: '¿Estas Seguro que deseas eliminar esta Promoción?' }%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
  <div>
    <h1>No hay promociones todavia</h1>
  </div>
<% end %>
    <br>

    <%= link_to 'Añadir Promoción', new_resto_promo_path, class: "new-item"  %>
  </div>
</div>

app/views/promos/new.html.erb
<div class="contenedor">
  <div class="canvas edit-content">
    <h1>Creando Promoción</h1>

    <%= render 'form' %>

    <%= link_to resto_promos_path,class: "volver" do %>
      <i class="fa fa-angle-left "></i>
      <p>Volver a Promociones</p> 
    <% end %>

  </div>
</div>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>