config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :owners, :controllers => { :registrations => "owners"}

  devise_scope :owner do
    authenticated :owner do
      root :to => 'restos#show', as: :authenticated_root
    end
  end

  root to: 'home#index'

  
  resources :restos do
    member do 
      get :data
      post :publish_resto
      post :unpublish_resto
    end
    collection do
      get :get_restos
    end
    resources :menus
    resources :promos
    resources :configurations
  end

  get "api/restos/:id" => "restos_api#show_resto"

  get "api/resto/:id/"  => "restos#show_resto"

  get "api/resto/:id/menus" => "restos_api#menus"

  get "api/resto/:id/promos" => "restos_api#promos"

  post "api/search/:data" => "restos_api#search"

end

app/models/resto.rb
class Resto < ActiveRecord::Base
  include PgSearch

  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance

  attr_accessor :distance

  belongs_to :owner
  belongs_to :resto_tipo
  has_many :promos
  has_many :menus
  has_many :subscriptions

  has_attached_file :avatar, styles: {
    thumb: '160x160>',
    medium: '300x300>',
    large: '800x800>'
  },

  :url => ':s3_alias_url',
  :s3_host_alias => 'd27tkdf0qa4ye1.cloudfront.net'

  validates_attachment_size :avatar, less_than: 2.megabyte

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  after_destroy :refresh_cache
  after_save :refresh_cache

  pg_search_scope :search, :against => [:name],:using => { :tsearch => {:prefix => true} }

  validates :details, presence: true


  def calculate_distance(location)
    self.distance = self.distance_to(location,:units=>:kms,:formula => :sphere).round(1)
  end

  def self.cached_restos
    Rails.cache.fetch("restos") { where(online: true).to_a }
  end

  def refresh_cache
    Rails.cache.delete("restos")
  end

  def set_online
    self.online = true
    save
  end

  def past_due?
    self.subscriptions.where(active: true).blank?
  end

end

app/controllers/restos_controller.rb
class RestosController < ApplicationController
  before_filter :authenticate_owner!, except: [:get_restos, :data, :show_resto]
  before_action :set_resto, except: [:get_restos, :show]

  def get_restos
    if !params[:lat].blank? && !params[:lng].blank?
      location = params[:lat], params[:lng]
      #revisar cuando esten muchos restaurantes disponibles , restringir la busqueda por cercania
      @restos = Resto.where(online: true)
      @restos.each do |resto|
        resto.calculate_distance(location)
      end
      sorted_restos = @restos.sort_by{|e| e.distance}
      @restos = sorted_restos.paginate(:page => params[:page],:per_page => params[:per_page])
      render json: @restos, each_serializer: ApiRestoSerializer, root: false
    else
      restos = Resto.where(online: true)
      @restos = restos.paginate(:page => params[:page], :per_page => params[:per_page])
      render json: @restos, each_serializer: ApiRestoSerializer, root: false
    end
  end

  def show_resto
    location = params[:lat], params[:lng]
    @resto.calculate_distance(location)
    render json: @resto,  root: false
  end

  def publish_resto
    @resto = current_owner.resto
    if not @resto.past_due?
      @resto.update(online: true)
      redirect_to :back
    else
      redirect_to :back
      flash["error"] = "Ups hubo un error"
    end
  end

  def unpublish_resto
    @resto = current_owner.resto
    if not @resto.past_due?
      @resto.update(online: false)
      redirect_to :back
    else
      redirect_to :back
      flash["error"] = "Ups hubo un error"
    end
  end

  def data
    resto_params = [:direccion,:telefono,:lat,:lng,:hasReservas,:hasParking,:hasTickets,:hasWifi,:has_delivery,:horario]
    return render json:{ resto: @resto.as_json(only: resto_params),menus: @resto.menus.as_json(:methods => [:image_url]), promos: @resto.promos.as_json(:methods => [:image_url]) }
  end

  def update
    if @resto.update(resto_params)
      flash[:notice] = "Cambio realizados exitosamente"
      redirect_to resto_path(@resto)
    else
      flash[:alert] = "Debes rellenar todos los campos."
      redirect_to :back
    end
  end

  def show
    @resto = current_owner.resto
    @past_due = current_owner.resto.past_due?
  end

  private
    def set_resto
      @resto = Resto.find(params[:id])
    end

    def resto_params
        params.require(:resto).permit(:name,:details,
                                      :direccion,:horario,
                                      :tipo,:telefono,:hasWifi,
                                      :hasFumadores,:hasParking,
                                      :hasTickets,:hasMenu,
                                      :hasReservas,:hasDelivery,:avatar,:resto_tipo_id)
    end

end

app/helpers/restos_helper.rb
module RestosHelper
end

app/views/restos/_form.html.erb
<script type="text/javascript">
   $("form").submit(function(){
    console.log("submit")
    $("form input:submit").prop("disabled", true)
  });
</script>

<div class="edit-resto">
  <%= form_for @resto do |f| %>
  <div class="detalles margin-top">
    <p>Detalles</p>
    <%= f.text_area :details,:maxlength => 85 ,:size => "30x2"%>
  </div>
  <div class="margin-top">
    <p>Telefono</p>
    <%= f.text_field :telefono %>
  </div>
  <div class="margin-top">
    <p>Atributos</p>
    <div>
      <%= f.check_box :hasReservas %>
      <%= f.label :reservas  %>
    </div>
    <div>
      <%= f.check_box :hasParking %>
      <%= f.label :estacionamiento  %>
    </div>
    <div>
      <%= f.check_box :hasTickets %>
      <%= f.label :cheque_restaurant  %>
    </div>
    <div>
      <%= f.check_box :hasWifi %>
      <%= f.label :wifi  %>
    </div>
    <div>
      <%= f.check_box :hasDelivery %>
      <%= f.label :delivery  %>
    </div>
  </div>
  <div class="margin-top">
    <p>Tipo</p>
    <%= f.select :resto_tipo_id, options_from_collection_for_select(RestoTipo.all, :id, :name)  %>
  </div>
  <div class="margin-top">
    <p>Imagen</p>
    <%= f.file_field :avatar %>
  </div>
	<div id="horario" class="margin-top">
    <p>Horario</p>
  	<%= f.text_field :horario %>
	</div>
  <div class="actions ">
    <%= f.submit  "Actualizar Información", class: "update-attr"%>
  </div>
  <% end %>

</div>

app/views/restos/edit.html.erb
<h1>Editando Resto</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/restos/index.html.erb
<h1>Restos#index</h1>
<p>Find me in app/views/restos/index.html.erb</p>

app/views/restos/show.html.erb
<div class="contenedor" ng-app="RestoImage">
  <div class="canvas-home">
    <div class="col-md-6 padding-right-none">
      <%= render "restos/form" %>
    </div>
    <div class="info-resto">
      <div class="header-resto">
        <% if @resto.online %>
          <h4 class="online">Online</h4>
        <% else %>
          <h4 class="offline">Offline</h4>
        <% end %>
        <h2><%= @resto.name %></h2>
        <%= image_tag @resto.avatar %>
        <% if not @past_due %>
          <div class="state-change">
            <% if @resto.online %>
              <%= link_to "Dejar de publicar en la app", unpublish_resto_resto_path(current_owner.resto) ,class: "red", method: :post %>
            <% else %>
              <%= link_to "Publicar en la app", publish_resto_resto_path(current_owner.resto) ,class: "green", method: :post %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>